### ISSUE TITLE
Issue with jupyter notebook

### ISSUE THREAD

**Issue by ModMaamari** [jjhelmus/berryconda#59]
When I try to run :
`jupyter notebook
`
I get this error :

```
Traceback (most recent call last):
  File "/home/pi/berryconda3/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/home/pi/berryconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 46, in <module>
    from zmq.eventloop import ioloop
  File "/home/pi/berryconda3/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/home/pi/berryconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/pi/berryconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/pi/berryconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/pi/berryconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/pi/berryconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/pi/berryconda3/lib/python3.6/site-packages/zmq/backend/cython/../../../../../libzmq.so.5)

```

I installed jupyter notebook using conda, and I checked that it is installed and it is in (conda list)

How can I run jupyter notebook ?

**Comment by jjhelmus** [comment]
@ModMaamari What version of Rasbian are you running?  You may need to update to a newer version.

**Comment by ModMaamari** [comment]
>> `uname -a`
`Linux pi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux`

**Comment by ModMaamari** [comment]
Is the cause of the error is the version of my OS?
HELP PLEASE !!

FYI :
ipython is working without any errors, but jupyter is not wrking.
`>>ipython
Python 3.6.1 | packaged by rpi | (default, Apr 20 2017, 19:35:19) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: 
`
`>>uname -a
Linux pi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux`
_______________________________________________________________________________________________________
`>>cat /etc/os-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"`
_______________________________________________________________________________________________________
`>>conda list
# packages in environment at /home/pi/berryconda3:
#
# Name                    Version                   Build  Channel
asn1crypto                0.22.0                   py36_0  
backcall                  0.1.0                      py_0  
backports                 1.0                        py_2  
backports.functools_lru_cache 1.5                        py_1  
blas                      1.1                    openblas  
bleach                    2.1.4                      py_1  
ca-certificates           2018.8.24                     0  
certifi                   2018.8.24                py36_1  
cffi                      1.10.0                   py36_0  
chardet                   3.0.4                    py36_0  
conda                     4.5.11                   py36_0  
conda-env                 2.6.0                         0  
cryptography              1.9                      py36_0  
cycler                    0.10.0                     py_1  
cython                    0.28.5           py36h4f752ac_0  
decorator                 4.3.0                      py_0  
entrypoints               0.2.3                    py36_2  
freetype                  2.7                           0  
html5lib                  1.0.1            py36h4e0ed57_0  
idna                      2.5                      py36_0  
ipykernel                 4.9.0                    py36_0  
ipython                   6.5.0                    py36_0  
ipython_genutils          0.2.0                      py_1  
ipywidgets                7.4.1                      py_0  
jedi                      0.12.1                   py36_0  
jinja2                    2.10                       py_1  
jsonschema                2.6.0                    py36_2  
jupyter                   1.0.0            py36h224aed1_0  
jupyter_client            5.2.3                      py_1  
jupyter_console           5.2.0                    py36_1  
jupyter_core              4.4.0              pyhc2c3be9_0  
libffi                    3.2.1                         0  
libgfortran               3.0.0                         0  
libpng                    1.6.35               h849d6a0_1  
libsodium                 1.0.16                        0  
markupsafe                1.0              py36hdff2a78_1  
matplotlib                2.1.2            py36hdcec099_0  
mistune                   0.8.3            py36hdff2a78_2  
nbconvert                 5.3.1                      py_1  
nbformat                  4.4.0                      py_1  
ncurses                   5.9                           0  
notebook                  5.6.0                    py36_1  
numpy                     1.15.1          py36_blas_openblash28c00a7_1  [blas_openblas]
openblas                  0.2.19                        0  
openssl                   1.0.2q               hdff2a78_0  
packaging                 16.8                     py36_0  
pandas                    0.23.4           py36h6b76cdf_0  
pandocfilters             1.4.2                      py_1  
parso                     0.3.1                      py_0  
patsy                     0.5.0                      py_1  
pexpect                   4.6.0                    py36_0  
pickleshare               0.7.4                    py36_0  
pip                       9.0.1                    py36_0  
prometheus_client         0.3.1                      py_1  
prompt_toolkit            1.0.15                     py_0  
ptyprocess                0.6.0                    py36_0  
pycosat                   0.6.3            py36hdff2a78_1  
pycparser                 2.17                     py36_0  
pygments                  2.2.0                      py_1  
pyopenssl                 16.2.0                   py36_0  
pyparsing                 2.2.0                    py36_0  
python                    3.6.1                         0  
python-dateutil           2.6.1                      py_0  
pytz                      2018.5                     py_0  
pyzmq                     17.1.2           py36h7dfa1d7_0  
readline                  6.3                           0  
requests                  2.18.1                   py36_0  
ruamel_yaml               0.11.14                  py36_0  
scikit-learn              0.19.2          py36_blas_openblasha91e181_201  [blas_openblas]
scipy                     1.0.0            py36h741f5fb_0  
seaborn                   0.9.0                      py_0  
send2trash                1.5.0                      py_0  
setuptools                36.0.1                   py36_0  
simplegeneric             0.8.1                      py_1  
six                       1.10.0                   py36_0  
sqlite                    3.15.0                        0  
statsmodels               0.9.0                    py36_0  
terminado                 0.8.1                    py36_1  
testpath                  0.3.1                    py36_1  
tk                        8.6.6                         0  
tornado                   5.1              py36hdff2a78_1  
traitlets                 4.3.2                    py36_0  
urllib3                   1.21.1                   py36_0  
wcwidth                   0.1.7                      py_1  
webencodings              0.5.1                      py_1  
wheel                     0.29.0                   py36_0  
widgetsnbextension        3.4.1                    py36_0  
xz                        5.2.2                         0  
yaml                      0.1.6                         0  
zeromq                    4.2.5                h4f752ac_5  
zlib                      1.2.11                        0  
`
_______________________________________________________________________________________________________
`>> conda --version
conda 4.5.11
`
_______________________________________________________________________________________________________
`>>jupyter --version
4.4.0
`
_______________________________________________________________________________________________________
`>>jupyter --paths
config:
    /home/pi/.jupyter
    /home/pi/berryconda3/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /home/pi/.local/share/jupyter
    /home/pi/berryconda3/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /run/user/1000/jupyter
`
_______________________________________________________________________________________________________
`>>pwd
/home/pi
`_______________________________________________________________________________________________________
`>>jupyter notebook
Traceback (most recent call last):
  File "/home/pi/berryconda3/bin/jupyter-notebook", line 7, in <module>
    from notebook.notebookapp import main
  File "/home/pi/berryconda3/lib/python3.6/site-packages/notebook/notebookapp.py", line 46, in <module>
    from zmq.eventloop import ioloop
  File "/home/pi/berryconda3/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/home/pi/berryconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/pi/berryconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/pi/berryconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/pi/berryconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/pi/berryconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /home/pi/berryconda3/lib/python3.6/site-packages/zmq/backend/cython/../../../../../libzmq.so.5)
`
_______________________________________________________________________________________________________

PLEASE HELP!

**Comment by jjhelmus** [comment]
> VERSION="8 (jessie)"

You need to update to stretch to use the berryconda packages.  Older packages were built to support jessie but newer packages require stretch.

**Comment by ModMaamari** [comment]
Thanks, I'll try to update it, hope that solves the problem :)
